#!/bin/bash
/home/rschwalk/dotfiles/scripts/backups/backup_photo_usb.sh;
/home/rschwalk/dotfiles/scripts/backups/backup_photo_nas.sh;
/home/rschwalk/dotfiles/scripts/backups/backup_video_usb.sh;
/home/rschwalk/dotfiles/scripts/backups/backup_video_nas.sh;
/home/rschwalk/dotfiles/scripts/backups/backup_music_nas.sh;
/home/rschwalk/dotfiles/scripts/backups/backup_foto_nas.sh;
/home/rschwalk/dotfiles/scripts/backups/backup_home_nas.sh;
/home/rschwalk/dotfiles/scripts/backups/backup_sonst_nas.sh;
/home/rschwalk/dotfiles/scripts/backups/backup_spi_nas.sh;